// This file is generated from src/ink/chapters by
// scripts/generate-story-prefetch-plan.mjs. Do not edit it by hand.

export type StorySpritePrefetchEntry = readonly [characterId: string, expression: string];

export const storyAssetSequenceByChapter: Readonly<Record<number, readonly string[]>> = {
    "1": [
        "ch01-university-walkway-afternoon",
        "ch01-takeda-collapse-cg",
        "ch01-university-walkway-afternoon",
        "ch01-cg-060-takeda-shower-flashback",
        "ch01-university-walkway-afternoon",
        "ch01-cg-068-fuutarou-bakery-memory-hesitation",
        "ch01-cg-069-miku-bakery-training-hands-close",
        "ch01-cg-070-miku-bakery-training-counter-close",
        "ch01-university-walkway-afternoon",
        "ch01-arched-passage-afternoon",
        "ch01-cg-065-walk-denial",
        "ch01-cg-066-walk-denial-continuation",
        "ch01-cg-067-walk-denial-exposed",
        "ch01-arched-passage-afternoon",
        "ch01-cg-072-miku-fuutarou-rooftop-close-memory",
        "ch01-student-residence-approach",
        "ch01-cg-064-fuutarou-hot-springs-smile",
        "ch01-cg-064-5-takeda-chibi-teases",
        "ch01-student-residence-approach",
        "ch01-cg-061-fuutarou-nostalgic-smile",
        "ch01-cg-062-takeda-notices-smile",
        "ch01-cg-063-takeda-teases-fuutarou",
        "ch01-student-residence-restroom",
        "ch01-cg-071-takeda-hug-attempt-extra"
    ],
    "2": [
        "ch02-uesugi-home-exterior-morning-motorcycle",
        "ch02-uesugi-entryway-inside-morning",
        "ch02-uesugi-main-room-note-table",
        "ch02-raiha-note-closeup",
        "ch02-uesugi-radio-weather",
        "ch02-warlords-gifts-drawer",
        "ch02-onsen-arrival-parking",
        "ch02-onsen-ryokan-forest-entrance",
        "onsen-cg-001-raiha-reunion",
        "ch02-onsen-ryokan-forest-entrance"
    ],
    "3": [
        "ch02-onsen-ryokan-forest-entrance-rain",
        "ch02-onsen-womens-bath-vestibule",
        "onsen-cg-002-bath-door-accident",
        "ch02-onsen-womens-bath-vestibule",
        "ch02-onsen-courtyard-window-corridor",
        "onsen-cg-003-grandpa-thanks-fuutarou",
        "ch02-onsen-courtyard-window-corridor",
        "onsen-cg-054-grandpa-asks-if-fuutarou-is-happy",
        "ch02-onsen-courtyard-window-corridor",
        "ch02-onsen-uesugi-family-tatami-room",
        "ch02-onsen-courtyard-window-corridor",
        "ch02-onsen-destiny-bell-overlook",
        "onsen-cg-004-fuutarou-destiny-bell",
        "ch02-onsen-destiny-bell-overlook",
        "ch02-onsen-destiny-bell-overlook"
    ],
    "4": [
        "ch02-onsen-quintuplets-tatami-room",
        "onsen-cg-005-kotatsu-love-conversation",
        "ch02-onsen-quintuplets-tatami-room",
        "onsen-cg-006-yotsuba-asks-sisters-help",
        "ch02-onsen-quintuplets-tatami-room"
    ],
    "5": [
        "ch02-onsen-uesugi-family-tatami-room",
        "ch02-onsen-courtyard-window-corridor",
        "onsen-cg-007-four-rena-lineup",
        "ch02-onsen-courtyard-window-corridor",
        "onsen-cg-008-nino-covers-fuutarou-eyes",
        "ch02-onsen-courtyard-window-corridor",
        "ch02-onsen-quintuplets-tatami-room",
        "onsen-cg-009-ichika-head-pat",
        "ch02-onsen-quintuplets-tatami-room",
        "ch02-onsen-reception-staircase",
        "onsen-cg-010-itsuki-grateful-smile",
        "ch02-onsen-reception-staircase",
        "ch02-onsen-stairwell-landing",
        "onsen-cg-011-yotsuba-final-rena-reveal"
    ],
    "6": [
        "ch02-onsen-stairwell-landing",
        "onsen-cg-012-fuutarou-approaches-yotsuba",
        "ch02-onsen-stairwell-landing",
        "onsen-cg-013-yotsuba-breakup",
        "ch02-onsen-stairwell-landing",
        "onsen-cg-014-yotsuba-pushes-fuutarou",
        "ch02-onsen-stairwell-landing",
        "onsen-cg-053-yotsuba-hears-miku-name",
        "onsen-cg-015-fuutarou-yotsuba-farewell-hug",
        "ch02-onsen-stairwell-landing",
        "onsen-cg-016-present-childhood-farewell",
        "ch02-onsen-stairwell-landing",
        "onsen-cg-017-sisters-hold-crying-yotsuba",
        "ch02-onsen-reception-staircase",
        "onsen-cg-018-maruo-throws-umbrella",
        "ch02-onsen-reception-staircase",
        "ch02-onsen-stairwell-landing"
    ],
    "7": [
        "ch07-asahiyama-high-school-corridor-afternoon",
        "onsen-cg-019-young-isanari-confession",
        "ch07-asahiyama-high-school-corridor-afternoon",
        "ch07-asahiyama-school-nurse-office-afternoon",
        "ch07-asahiyama-high-school-corridor-afternoon",
        "onsen-cg-020-aoi-isanari-life-montage",
        "ch07-cg-051-isanari-proposes-to-aoi",
        "onsen-cg-020-aoi-isanari-life-montage",
        "ch07-aoi-isanari-bakery-interior-struggling",
        "ch07-cg-052-uesugi-family-bakery-memory",
        "ch07-aoi-isanari-bakery-interior-struggling",
        "ch07-aoi-isanari-bakery-exterior-struggling",
        "ch07-aoi-isanari-bakery-interior-struggling",
        "ch07-aoi-isanari-bakery-exterior-struggling",
        "ch07-aoi-isanari-bakery-interior-struggling",
        "ch07-aoi-hospital-room-night",
        "onsen-cg-021-aoi-hospital-farewell",
        "ch07-uesugi-main-room-night",
        "onsen-cg-022-isanari-breakdown-at-home",
        "ch02-onsen-reception-staircase",
        "onsen-cg-023-isanari-cries-before-maruo",
        "ch02-onsen-reception-staircase",
        "ch02-onsen-upper-ryokan-motorcycle-forecourt",
        "onsen-cg-024-raiha-motorcycle-farewell",
        "ch02-onsen-upper-ryokan-motorcycle-forecourt",
        "onsen-cg-025-fuutarou-meets-ren",
        "ch02-onsen-upper-ryokan-motorcycle-forecourt",
        "onsen-cg-026-maruo-ren-watch-descent",
        "ch02-onsen-upper-ryokan-motorcycle-forecourt",
        "ch02-onsen-reception-staircase"
    ],
    "8": [
        "ch02-onsen-upper-ryokan-motorcycle-forecourt",
        "ch08-mountain-descent-road",
        "ch08-yuzine-eien-street",
        "ch08-yuzine-eien-street-rain",
        "onsen-cg-027-miku-rainy-bench-reunion",
        "ch08-yuzine-eien-street-rain",
        "onsen-cg-042-miku-bell-kiss-flashback",
        "ch08-yuzine-eien-street-rain",
        "onsen-cg-043-miku-removes-wig-crying",
        "ch08-yuzine-eien-street-rain",
        "onsen-cg-044-fuutarou-reveals-miku-face",
        "onsen-cg-028-fuutarou-miku-bell-confession-kiss",
        "ch08-yuzine-eien-street-rain",
        "onsen-cg-045-fuutarou-initiates-rain-kiss",
        "ch08-yuzine-eien-street-rain",
        "ch08-cg-041a-miku-answer-permission",
        "ch08-yuzine-eien-street-rain",
        "ch08-cg-041b-miku-steps-closer",
        "ch08-cg-041c-miku-embraces-fuutarou",
        "ch08-cg-041d-miku-almost-kiss",
        "ch08-cg-041e-miku-initiates-kiss",
        "ch08-cg-041f-fuutarou-returns-kiss",
        "ch08-yuzine-eien-street-rain",
        "onsen-cg-029-fuutarou-miku-umbrella-walk",
        "ch08-yuzine-eien-street",
        "ch08-yuzine-eien-street"
    ],
    "9": [
        "ch09-miku-pickup-street-late-morning",
        "onsen-cg-046-miku-fuutarou-seven-month-reunion",
        "ch09-miku-pickup-street-late-morning",
        "ch09-date-restaurant-interior-late-morning",
        "ch09-local-library-interior-afternoon",
        "ch09-asahiyama-high-school-exterior",
        "ch07-asahiyama-high-school-corridor-afternoon",
        "ch09-asahiyama-rooftop-sunset",
        "onsen-cg-030-fuutarou-miku-rooftop-dance",
        "ch09-asahiyama-rooftop-sunset",
        "onsen-cg-047-fuutarou-rooftop-proposal-question",
        "onsen-cg-048-miku-processes-rooftop-proposal",
        "onsen-cg-031-miku-accepts-rooftop-proposal",
        "onsen-cg-049-miku-fuutarou-rooftop-yes-kiss",
        "ch09-asahiyama-rooftop-sunset",
        "ch09-asahiyama-rooftop-early-night",
        "onsen-cg-050-miku-listens-to-fuutarou-heartbeat"
    ],
    "10": [
        "ch10-sutekina-church-interior-altar",
        "wedding-cg-032-miku-fuutarou-wedding-kiss",
        "ch10-sutekina-reception-hall-evening",
        "wedding-cg-055-family-photo",
        "ch10-sutekina-reception-hall-evening",
        "wedding-cg-033-miku-maruo-family-dance",
        "ch10-sutekina-reception-hall-evening",
        "wedding-cg-034-miku-kisses-frosting-from-fuutarou",
        "ch10-sutekina-reception-hall-evening",
        "wedding-cg-035-miku-thanks-her-sisters",
        "ch10-sutekina-church-exterior-courtyard-dusk",
        "wedding-cg-056-farewell-to-ryokan",
        "ch10-sutekina-church-exterior-courtyard-dusk",
        "wedding-cg-036-yotsuba-catches-wedding-bouquet",
        "ch10-sutekina-church-exterior-courtyard-dusk",
        "wedding-cg-037-sisters-receive-wedding-keepsakes",
        "ch10-wedding-limousine-interior-eien-street-evening",
        "wedding-cg-057-limousine-kiss"
    ],
    "11": [
        "wedding-cg-038-sisters-career-montage",
        "ch11-uesugi-bakery-exterior-renovated",
        "ch11-uesugi-bakery-interior-renovated",
        "wedding-cg-039-family-visits-new-bakery",
        "wedding-cg-058-miku-ring-new-family-reveal",
        "wedding-cg-040-miku-memory-desk-finale",
        "wedding-cg-059-fuutarou-leads-miku-to-future"
    ]
};

export const storySpriteSequenceByChapter: Readonly<Record<number, readonly StorySpritePrefetchEntry[]>> = {
    "1": [
        [
            "fuutarou",
            "chapter_01_neutral"
        ],
        [
            "takeda",
            "enthusiastic"
        ],
        [
            "takeda",
            "exhausted"
        ],
        [
            "fuutarou",
            "chapter_01_annoyed"
        ],
        [
            "takeda",
            "sparkle"
        ],
        [
            "fuutarou",
            "chapter_01_surprised"
        ],
        [
            "fuutarou",
            "chapter_01_annoyed"
        ],
        [
            "fuutarou",
            "chapter_01_annoyed"
        ],
        [
            "takeda",
            "sparkle"
        ],
        [
            "fuutarou",
            "chapter_01_hand_cover"
        ],
        [
            "fuutarou",
            "chapter_01_hand_cover"
        ],
        [
            "fuutarou",
            "chapter_01_hand_cover"
        ],
        [
            "takeda",
            "sparkle"
        ],
        [
            "fuutarou",
            "chapter_01_annoyed"
        ],
        [
            "takeda",
            "supportive"
        ],
        [
            "fuutarou",
            "chapter_01_neck_scratch"
        ],
        [
            "takeda",
            "supportive"
        ],
        [
            "fuutarou",
            "chapter_01_surprised"
        ],
        [
            "takeda",
            "arms_crossed"
        ],
        [
            "fuutarou",
            "chapter_01_hand_cover"
        ],
        [
            "fuutarou",
            "chapter_01_neutral"
        ],
        [
            "takeda",
            "sheepish"
        ],
        [
            "fuutarou",
            "chapter_01_surprised"
        ],
        [
            "takeda",
            "sheepish"
        ],
        [
            "fuutarou",
            "chapter_01_neutral"
        ],
        [
            "fuutarou",
            "chapter_01_annoyed"
        ],
        [
            "takeda",
            "sparkle"
        ]
    ],
    "2": [
        [
            "fuutarou",
            "neutral"
        ],
        [
            "fuutarou",
            "sad"
        ],
        [
            "fuutarou",
            "neck_scratch"
        ],
        [
            "fuutarou",
            "neutral"
        ],
        [
            "fuutarou",
            "neutral"
        ],
        [
            "fuutarou",
            "annoyed"
        ],
        [
            "fuutarou",
            "neutral"
        ],
        [
            "fuutarou",
            "worried"
        ],
        [
            "fuutarou",
            "sad"
        ],
        [
            "isanari",
            "boisterous_laugh"
        ],
        [
            "raiha",
            "neutral"
        ],
        [
            "raiha",
            "concerned_scold"
        ],
        [
            "maruo",
            "onsen_travel_neutral"
        ],
        [
            "ichika",
            "neutral"
        ],
        [
            "nino",
            "neutral"
        ],
        [
            "itsuki",
            "neutral"
        ],
        [
            "raiha",
            "cheerful_wave"
        ],
        [
            "isanari",
            "cheerful"
        ],
        [
            "maruo",
            "onsen_travel_stern"
        ],
        [
            "isanari",
            "awkward"
        ],
        [
            "ichika",
            "teasing"
        ],
        [
            "nino",
            "neutral"
        ],
        [
            "itsuki",
            "neutral"
        ],
        [
            "yotsuba",
            "wave"
        ],
        [
            "yotsuba",
            "nervous"
        ],
        [
            "itsuki",
            "thoughtful"
        ],
        [
            "raiha",
            "neutral"
        ],
        [
            "nino",
            "angry"
        ],
        [
            "yotsuba",
            "nervous"
        ],
        [
            "ichika",
            "warm_smile"
        ],
        [
            "itsuki",
            "indignant"
        ],
        [
            "raiha",
            "surprised_shy"
        ],
        [
            "maruo",
            "onsen_travel_soft_smile"
        ]
    ],
    "3": [
        [
            "fuutarou",
            "neutral"
        ],
        [
            "fuutarou",
            "neck_scratch"
        ],
        [
            "fuutarou",
            "hand_cover"
        ],
        [
            "fuutarou",
            "neutral"
        ],
        [
            "nino",
            "onsen_yukata_neutral"
        ],
        [
            "yotsuba",
            "onsen_yukata_nervous"
        ],
        [
            "ichika",
            "onsen_yukata_neutral"
        ],
        [
            "nino",
            "onsen_yukata_annoyed"
        ],
        [
            "ichika",
            "onsen_yukata_concerned"
        ],
        [
            "fuutarou",
            "neck_scratch"
        ],
        [
            "fuutarou",
            "neutral"
        ],
        [
            "grandpa",
            "neutral"
        ],
        [
            "maruo",
            "onsen_travel_stern"
        ],
        [
            "fuutarou",
            "surprised"
        ],
        [
            "grandpa",
            "gentle"
        ],
        [
            "maruo",
            "onsen_travel_concerned"
        ],
        [
            "grandpa",
            "gentle"
        ],
        [
            "maruo",
            "onsen_travel_composed"
        ],
        [
            "yotsuba",
            "onsen_yukata_wave"
        ],
        [
            "fuutarou",
            "neutral"
        ],
        [
            "fuutarou",
            "neck_scratch"
        ],
        [
            "fuutarou",
            "neutral"
        ],
        [
            "grandpa",
            "neutral"
        ],
        [
            "fuutarou",
            "hand_cover"
        ],
        [
            "grandpa",
            "gentle"
        ],
        [
            "grandpa",
            "authoritative"
        ],
        [
            "grandpa",
            "frail_tired"
        ],
        [
            "grandpa",
            "regretful"
        ],
        [
            "grandpa",
            "grateful"
        ],
        [
            "fuutarou",
            "neutral"
        ],
        [
            "grandpa",
            "grateful"
        ],
        [
            "grandpa",
            "concerned"
        ],
        [
            "fuutarou",
            "hand_cover"
        ],
        [
            "fuutarou",
            "annoyed"
        ],
        [
            "fuutarou",
            "neutral"
        ],
        [
            "fuutarou",
            "neck_scratch"
        ],
        [
            "fuutarou",
            "surprised"
        ],
        [
            "grandpa",
            "relieved_smile"
        ]
    ],
    "4": [
        [
            "ichika",
            "onsen_yukata_neutral"
        ],
        [
            "yotsuba",
            "onsen_yukata_nervous"
        ],
        [
            "nino",
            "onsen_yukata_annoyed"
        ],
        [
            "itsuki",
            "onsen_yukata_neutral"
        ],
        [
            "nino",
            "onsen_yukata_neutral"
        ],
        [
            "itsuki",
            "onsen_yukata_joyful"
        ],
        [
            "yotsuba",
            "onsen_yukata_nervous"
        ],
        [
            "ichika",
            "onsen_yukata_concerned"
        ],
        [
            "yotsuba",
            "onsen_yukata_nervous"
        ],
        [
            "nino",
            "onsen_yukata_annoyed"
        ],
        [
            "itsuki",
            "onsen_yukata_surprised"
        ],
        [
            "yotsuba",
            "onsen_yukata_nervous"
        ],
        [
            "nino",
            "onsen_yukata_soft"
        ],
        [
            "ichika",
            "onsen_yukata_sad_reflective"
        ],
        [
            "itsuki",
            "onsen_yukata_thoughtful"
        ],
        [
            "itsuki",
            "onsen_yukata_joyful"
        ],
        [
            "nino",
            "onsen_yukata_proud"
        ],
        [
            "ichika",
            "onsen_yukata_teasing"
        ],
        [
            "yotsuba",
            "onsen_yukata_sad_smile"
        ],
        [
            "yotsuba",
            "onsen_yukata_determined"
        ],
        [
            "yotsuba",
            "onsen_yukata_neutral"
        ],
        [
            "itsuki",
            "onsen_yukata_flustered"
        ]
    ],
    "5": [
        [
            "raiha",
            "determined"
        ],
        [
            "raiha",
            "gentle_worry"
        ],
        [
            "isanari",
            "hungover"
        ],
        [
            "raiha",
            "concerned_scold"
        ],
        [
            "rena",
            "hidden"
        ],
        [
            "nino",
            "rena_disguise_proud"
        ],
        [
            "nino",
            "rena_disguise_annoyed"
        ],
        [
            "nino",
            "rena_disguise_happy"
        ],
        [
            "nino",
            "rena_disguise_soft"
        ],
        [
            "nino",
            "rena_disguise_embarrassed"
        ],
        [
            "rena",
            "hidden"
        ],
        [
            "ichika",
            "rena_disguise_teasing"
        ],
        [
            "ichika",
            "rena_disguise_sad_reflective"
        ],
        [
            "ichika",
            "rena_disguise_warm_smile"
        ],
        [
            "ichika",
            "rena_disguise_embarrassed"
        ],
        [
            "ichika",
            "rena_disguise_laughing"
        ],
        [
            "rena",
            "hidden"
        ],
        [
            "itsuki",
            "rena_disguise_neutral"
        ],
        [
            "itsuki",
            "rena_disguise_indignant"
        ],
        [
            "itsuki",
            "rena_disguise_flustered"
        ],
        [
            "itsuki",
            "rena_disguise_thoughtful"
        ],
        [
            "rena",
            "hidden"
        ]
    ],
    "6": [
        [
            "yotsuba",
            "rena_disguise_neutral"
        ],
        [
            "yotsuba",
            "rena_disguise_nervous"
        ],
        [
            "yotsuba",
            "rena_disguise_sad_smile"
        ],
        [
            "yotsuba",
            "rena_disguise_determined"
        ],
        [
            "yotsuba",
            "rena_disguise_shocked"
        ],
        [
            "yotsuba",
            "rena_disguise_determined"
        ],
        [
            "yotsuba",
            "rena_disguise_determined"
        ],
        [
            "yotsuba",
            "rena_disguise_sad_smile"
        ],
        [
            "yotsuba",
            "rena_disguise_nervous"
        ],
        [
            "yotsuba",
            "rena_disguise_shocked"
        ],
        [
            "yotsuba",
            "rena_disguise_cheerful"
        ],
        [
            "yotsuba",
            "rena_disguise_cheerful"
        ],
        [
            "yotsuba",
            "rena_disguise_crying"
        ],
        [
            "ebata",
            "polite_greeting"
        ],
        [
            "ebata",
            "service_bow"
        ],
        [
            "yotsuba",
            "rena_disguise_crying"
        ]
    ],
    "7": [
        [
            "isanari_young",
            "neutral"
        ],
        [
            "aoi",
            "bashful"
        ],
        [
            "isanari_young",
            "determined"
        ],
        [
            "aoi",
            "determined"
        ],
        [
            "isanari_young",
            "shocked"
        ],
        [
            "maruo_young",
            "neutral"
        ],
        [
            "shimoda_young",
            "frantic_warning"
        ],
        [
            "shimoda_young",
            "exasperated_scolding"
        ],
        [
            "isanari_young",
            "determined"
        ],
        [
            "maruo_young",
            "neutral"
        ],
        [
            "maruo_young",
            "stern"
        ],
        [
            "maruo_young",
            "awkward"
        ],
        [
            "aoi",
            "bakery_ill"
        ],
        [
            "aoi",
            "bakery_maternal"
        ],
        [
            "aoi",
            "bakery_ill"
        ],
        [
            "aoi",
            "bakery_cheerful_peace"
        ],
        [
            "aoi",
            "bakery_ill"
        ],
        [
            "aoi",
            "bakery_determined"
        ]
    ],
    "8": [
        [
            "miku",
            "chapter_08_thoughtful"
        ],
        [
            "miku",
            "chapter_08_startled_retreat"
        ],
        [
            "fuutarou",
            "chapter_08_neutral"
        ],
        [
            "miku",
            "chapter_08_gentle"
        ],
        [
            "fuutarou",
            "chapter_08_surprised"
        ],
        [
            "fuutarou",
            "chapter_08_neck_scratch"
        ],
        [
            "miku",
            "chapter_08_warm_laugh"
        ],
        [
            "fuutarou",
            "chapter_08_neck_scratch"
        ],
        [
            "fuutarou",
            "chapter_08_annoyed"
        ],
        [
            "miku",
            "chapter_08_serious"
        ],
        [
            "miku",
            "chapter_08_gentle"
        ],
        [
            "fuutarou",
            "chapter_08_neutral"
        ],
        [
            "fuutarou",
            "chapter_08_worried"
        ],
        [
            "miku",
            "chapter_08_hurt"
        ],
        [
            "miku",
            "chapter_08_serious"
        ],
        [
            "miku",
            "chapter_08_gentle"
        ],
        [
            "fuutarou",
            "chapter_08_hand_cover"
        ],
        [
            "miku",
            "chapter_08_thoughtful"
        ],
        [
            "miku",
            "chapter_08_warm_laugh"
        ],
        [
            "miku",
            "chapter_08_startled_retreat"
        ],
        [
            "fuutarou",
            "chapter_08_surprised"
        ],
        [
            "fuutarou",
            "chapter_08_determined"
        ],
        [
            "fuutarou",
            "chapter_08_worried"
        ],
        [
            "miku",
            "chapter_08_hurt"
        ],
        [
            "miku",
            "chapter_08_embarrassed"
        ],
        [
            "fuutarou",
            "chapter_08_determined"
        ],
        [
            "miku",
            "chapter_08_hurt"
        ],
        [
            "fuutarou",
            "chapter_08_worried"
        ],
        [
            "miku",
            "chapter_08_hurt"
        ],
        [
            "miku",
            "chapter_08_crying_guarded"
        ],
        [
            "miku",
            "chapter_08_crying_guarded"
        ],
        [
            "fuutarou",
            "chapter_08_determined"
        ],
        [
            "fuutarou",
            "chapter_08_determined"
        ],
        [
            "miku",
            "chapter_08_teary_smile"
        ],
        [
            "miku",
            "chapter_08_embarrassed"
        ],
        [
            "fuutarou",
            "chapter_08_hand_cover"
        ],
        [
            "miku",
            "chapter_08_embarrassed"
        ],
        [
            "miku",
            "chapter_08_playful_resolved"
        ],
        [
            "fuutarou",
            "chapter_08_surprised"
        ],
        [
            "fuutarou",
            "chapter_08_hand_cover"
        ],
        [
            "miku",
            "chapter_08_serious"
        ],
        [
            "fuutarou",
            "chapter_08_hand_cover"
        ],
        [
            "miku",
            "chapter_08_embarrassed"
        ],
        [
            "fuutarou",
            "chapter_08_worried"
        ],
        [
            "miku",
            "chapter_08_hurt"
        ],
        [
            "miku",
            "chapter_08_gentle"
        ],
        [
            "fuutarou",
            "chapter_08_determined"
        ],
        [
            "miku",
            "chapter_08_thoughtful"
        ],
        [
            "miku",
            "chapter_08_embarrassed"
        ],
        [
            "fuutarou",
            "chapter_08_worried"
        ],
        [
            "miku",
            "chapter_08_hurt"
        ],
        [
            "fuutarou",
            "chapter_08_determined"
        ],
        [
            "miku",
            "chapter_08_embarrassed"
        ],
        [
            "miku",
            "chapter_08_thoughtful"
        ],
        [
            "miku",
            "chapter_08_teary_smile"
        ],
        [
            "miku",
            "chapter_08_playful_resolved"
        ],
        [
            "miku",
            "chapter_08_playful_resolved"
        ],
        [
            "fuutarou",
            "chapter_08_hand_cover"
        ],
        [
            "fuutarou",
            "chapter_08_determined"
        ],
        [
            "fuutarou",
            "chapter_08_soft_smile"
        ],
        [
            "miku",
            "chapter_08_teary_smile"
        ],
        [
            "miku",
            "chapter_08_playful_resolved"
        ],
        [
            "fuutarou",
            "chapter_08_soft_smile"
        ],
        [
            "miku",
            "chapter_08_gentle"
        ],
        [
            "fuutarou",
            "chapter_08_neck_scratch"
        ],
        [
            "miku",
            "chapter_08_warm_laugh"
        ],
        [
            "miku",
            "chapter_08_playful_resolved"
        ],
        [
            "fuutarou",
            "chapter_08_soft_smile"
        ],
        [
            "miku",
            "chapter_08_playful_resolved"
        ],
        [
            "fuutarou",
            "chapter_08_hand_cover"
        ],
        [
            "fuutarou",
            "chapter_08_neck_scratch"
        ],
        [
            "miku",
            "chapter_08_embarrassed"
        ],
        [
            "fuutarou",
            "chapter_08_hand_cover"
        ],
        [
            "miku",
            "chapter_08_warm_laugh"
        ],
        [
            "fuutarou",
            "chapter_08_soft_smile"
        ]
    ],
    "9": [
        [
            "fuutarou",
            "chapter_09_worried"
        ],
        [
            "fuutarou",
            "chapter_09_annoyed"
        ],
        [
            "fuutarou",
            "chapter_09_surprised"
        ],
        [
            "miku",
            "chapter_09_bright_reunion"
        ],
        [
            "fuutarou",
            "chapter_09_embarrassed"
        ],
        [
            "miku",
            "chapter_09_pout"
        ],
        [
            "fuutarou",
            "chapter_09_hand_cover"
        ],
        [
            "fuutarou",
            "chapter_09_soft_smile"
        ],
        [
            "miku",
            "chapter_09_playful"
        ],
        [
            "miku",
            "chapter_09_bright_reunion"
        ],
        [
            "miku",
            "chapter_09_gentle"
        ],
        [
            "miku",
            "chapter_09_playful"
        ],
        [
            "fuutarou",
            "chapter_09_embarrassed"
        ],
        [
            "miku",
            "chapter_09_thoughtful"
        ],
        [
            "miku",
            "chapter_09_vulnerable"
        ],
        [
            "miku",
            "chapter_09_gentle"
        ],
        [
            "fuutarou",
            "chapter_09_soft_smile"
        ],
        [
            "miku",
            "chapter_09_gentle"
        ],
        [
            "miku",
            "chapter_09_playful"
        ],
        [
            "fuutarou",
            "chapter_09_annoyed"
        ],
        [
            "fuutarou",
            "chapter_09_surprised"
        ],
        [
            "miku",
            "chapter_09_gentle"
        ],
        [
            "fuutarou",
            "chapter_09_determined"
        ],
        [
            "fuutarou",
            "chapter_09_teacher_neutral"
        ],
        [
            "miku",
            "chapter_09_neutral"
        ],
        [
            "miku",
            "chapter_09_gentle"
        ],
        [
            "fuutarou",
            "chapter_09_teacher_neutral"
        ],
        [
            "miku",
            "chapter_09_teacher_enthusiastic"
        ],
        [
            "fuutarou",
            "chapter_09_teacher_neutral"
        ],
        [
            "raiha",
            "chapter_09_cheerful_wave"
        ],
        [
            "miku",
            "chapter_09_gentle"
        ],
        [
            "fuutarou",
            "chapter_09_soft_smile"
        ],
        [
            "raiha",
            "chapter_09_neutral"
        ],
        [
            "fuutarou",
            "chapter_09_annoyed"
        ],
        [
            "raiha",
            "chapter_09_surprised_shy"
        ],
        [
            "miku",
            "chapter_09_playful"
        ],
        [
            "fuutarou",
            "chapter_09_surprised"
        ],
        [
            "fuutarou",
            "chapter_09_soft_smile"
        ],
        [
            "fuutarou",
            "chapter_09_determined"
        ],
        [
            "fuutarou",
            "chapter_09_teacher_neutral"
        ],
        [
            "fuutarou",
            "chapter_09_determined"
        ],
        [
            "fuutarou",
            "chapter_09_worried"
        ],
        [
            "miku",
            "chapter_09_playful"
        ],
        [
            "fuutarou",
            "chapter_09_soft_smile"
        ],
        [
            "miku",
            "chapter_09_bright_reunion"
        ],
        [
            "fuutarou",
            "chapter_09_neck_scratch"
        ],
        [
            "miku",
            "chapter_09_startled"
        ],
        [
            "fuutarou",
            "chapter_09_embarrassed"
        ],
        [
            "miku",
            "chapter_09_thoughtful"
        ],
        [
            "fuutarou",
            "chapter_09_hand_cover"
        ],
        [
            "miku",
            "chapter_09_bright_reunion"
        ],
        [
            "miku",
            "chapter_09_gentle"
        ],
        [
            "fuutarou",
            "chapter_09_soft_smile"
        ],
        [
            "fuutarou",
            "chapter_09_determined"
        ],
        [
            "miku",
            "chapter_09_gentle"
        ],
        [
            "miku",
            "chapter_09_startled"
        ],
        [
            "fuutarou",
            "chapter_09_teary_relief"
        ],
        [
            "miku",
            "chapter_09_teary_smile"
        ],
        [
            "fuutarou",
            "chapter_09_embarrassed"
        ],
        [
            "fuutarou",
            "chapter_09_embarrassed"
        ],
        [
            "miku",
            "chapter_09_playful"
        ],
        [
            "fuutarou",
            "chapter_09_hand_cover"
        ]
    ],
    "10": [
        [
            "raiha",
            "chapter_10_bright_laugh"
        ],
        [
            "yotsuba",
            "chapter_10_cheerful"
        ],
        [
            "ichika",
            "chapter_10_warm_smile"
        ],
        [
            "yotsuba",
            "chapter_10_nervous"
        ],
        [
            "nino",
            "chapter_10_annoyed"
        ],
        [
            "ichika",
            "chapter_10_embarrassed"
        ],
        [
            "itsuki",
            "chapter_10_serious"
        ],
        [
            "yotsuba",
            "chapter_10_nervous"
        ],
        [
            "nino",
            "chapter_10_angry"
        ],
        [
            "yotsuba",
            "chapter_10_determined"
        ],
        [
            "itsuki",
            "chapter_10_serious"
        ],
        [
            "nino",
            "chapter_10_annoyed"
        ],
        [
            "ichika",
            "chapter_10_laughing"
        ],
        [
            "nino",
            "chapter_10_angry"
        ],
        [
            "nino",
            "chapter_10_annoyed"
        ],
        [
            "yotsuba",
            "chapter_10_nervous"
        ],
        [
            "itsuki",
            "chapter_10_serious"
        ],
        [
            "ichika",
            "chapter_10_teasing"
        ],
        [
            "yotsuba",
            "chapter_10_cheerful"
        ],
        [
            "ichika",
            "chapter_10_warm_smile"
        ],
        [
            "raiha",
            "chapter_10_surprised_shy"
        ],
        [
            "isanari",
            "chapter_10_protective_alarm"
        ],
        [
            "raiha",
            "chapter_10_exasperated"
        ],
        [
            "nino",
            "chapter_10_neutral"
        ],
        [
            "isanari",
            "chapter_10_boisterous_laugh"
        ],
        [
            "raiha",
            "chapter_10_exasperated"
        ],
        [
            "isanari",
            "chapter_10_boisterous_laugh"
        ],
        [
            "raiha",
            "chapter_10_exasperated"
        ],
        [
            "fuutarou",
            "chapter_10_soft_smile"
        ],
        [
            "miku",
            "chapter_10_joyful"
        ],
        [
            "yotsuba",
            "chapter_10_cheerful"
        ],
        [
            "raiha",
            "chapter_10_cheerful_wave"
        ],
        [
            "isanari",
            "chapter_10_proud_emotional"
        ],
        [
            "isanari",
            "chapter_10_proud_emotional"
        ],
        [
            "miku",
            "chapter_10_embarrassed"
        ],
        [
            "miku",
            "chapter_10_teary_smile"
        ],
        [
            "nino",
            "chapter_10_soft"
        ],
        [
            "fuutarou",
            "chapter_10_soft_smile"
        ],
        [
            "maruo",
            "chapter_10_composed"
        ],
        [
            "maruo",
            "chapter_10_pained_reflection"
        ],
        [
            "maruo",
            "chapter_10_soft_smile"
        ],
        [
            "fuutarou",
            "chapter_10_tender_relief"
        ],
        [
            "fuutarou",
            "chapter_10_formal_gratitude"
        ],
        [
            "fuutarou",
            "chapter_10_soft_smile"
        ],
        [
            "miku",
            "chapter_10_playful"
        ],
        [
            "miku",
            "chapter_10_proud"
        ],
        [
            "fuutarou",
            "chapter_10_surprised"
        ],
        [
            "fuutarou",
            "chapter_10_embarrassed"
        ],
        [
            "miku",
            "chapter_10_playful"
        ],
        [
            "matsui",
            "chapter_10_playful"
        ],
        [
            "takeda",
            "chapter_10_solemn"
        ],
        [
            "tsubaki",
            "chapter_10_amused"
        ],
        [
            "nino",
            "chapter_10_neutral"
        ],
        [
            "ichika",
            "chapter_10_teasing"
        ],
        [
            "itsuki",
            "chapter_10_thoughtful"
        ],
        [
            "yotsuba",
            "chapter_10_cheerful"
        ],
        [
            "itsuki",
            "chapter_10_surprised"
        ],
        [
            "tsubaki",
            "chapter_10_amused"
        ],
        [
            "takeda",
            "chapter_10_enthusiastic"
        ],
        [
            "tsubaki",
            "chapter_10_supportive"
        ],
        [
            "ichika",
            "chapter_10_laughing"
        ],
        [
            "yotsuba",
            "chapter_10_nervous"
        ],
        [
            "nino",
            "chapter_10_neutral"
        ],
        [
            "nino",
            "chapter_10_annoyed"
        ],
        [
            "ichika",
            "chapter_10_warm_smile"
        ],
        [
            "itsuki",
            "chapter_10_thoughtful"
        ],
        [
            "yotsuba",
            "chapter_10_nervous"
        ],
        [
            "ichika",
            "chapter_10_teasing"
        ],
        [
            "nino",
            "chapter_10_neutral"
        ],
        [
            "raiha",
            "chapter_10_bright_laugh"
        ],
        [
            "raiha",
            "chapter_10_cheerful_wave"
        ],
        [
            "itsuki",
            "chapter_10_thoughtful"
        ],
        [
            "yotsuba",
            "chapter_10_determined"
        ],
        [
            "yotsuba",
            "chapter_10_nervous"
        ],
        [
            "yotsuba",
            "chapter_10_shocked"
        ],
        [
            "itsuki",
            "chapter_10_surprised"
        ],
        [
            "ichika",
            "chapter_10_embarrassed"
        ],
        [
            "nino",
            "chapter_10_angry"
        ],
        [
            "yotsuba",
            "chapter_10_determined"
        ],
        [
            "ichika",
            "chapter_10_teasing"
        ],
        [
            "ichika",
            "chapter_10_laughing"
        ],
        [
            "yotsuba",
            "chapter_10_nervous"
        ],
        [
            "ichika",
            "chapter_10_warm_smile"
        ],
        [
            "yotsuba",
            "chapter_10_cheerful"
        ],
        [
            "itsuki",
            "chapter_10_thoughtful"
        ],
        [
            "nino",
            "chapter_10_annoyed"
        ],
        [
            "itsuki",
            "chapter_10_warm"
        ],
        [
            "nino",
            "chapter_10_angry"
        ],
        [
            "nino",
            "chapter_10_emotional"
        ],
        [
            "nino",
            "chapter_10_angry"
        ],
        [
            "nino",
            "chapter_10_soft"
        ],
        [
            "itsuki",
            "chapter_10_warm"
        ],
        [
            "itsuki",
            "chapter_10_surprised"
        ],
        [
            "itsuki",
            "chapter_10_warm"
        ]
    ],
    "11": []
};
